### ISSUE TITLE
Softlocked?

### ISSUE THREAD

**Issue by jamiet9** [bbl-team/Modpack-Support#18]
I got to the part where I need concrete powder but unfortunately all of the concrete in the void dimension fell into the void... Whoopsie. I can't seem to find a way to get gravel so that I can make concrete powder myself to progress. Also this discord link "https://discord.gg/benbenlaw" doesn't appear to be working?

**Comment by Azulear** [comment]
When you are in your base in the overworld execute the /sethome command.
After that go back into the void and destroy the void portal block. Now you can use the /home command to get back to your base.
When you enter the void again a new platform will generate.

The discord link is not working because there is one server boost missing for level 3 which is needed to use own links.

**Comment by jamiet9** [comment]
Awesome I will try this. Thank you for the speedy support :)
